databases:
  - name: vacant-bar
    user: vacant-bar
    plan: free
    region: oregon

services:
  - type: web
    name: vacant-bar
    plan: free
    region: oregon
    branch: main
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vacant-bar
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REACT_APP_GMAPS_API_BROWSER_KEY
        sync: false
      - key: REACT_APP_GMAPS_API_SERVER_KEY
        sync: false